Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,7 +28,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+          aws-region: $AWS_REGION
       
       - name: Install Dependencies
         run: |
@@ -38,7 +38,8 @@ jobs:
       - name: Mount EFS
         run: |
           sudo mkdir -p /mnt/efs
-          sudo mount -t nfs4 -o nfsvers=4.1,tcp,hard,timeo=600,retrans=2 fs-02bded1456fa64b56.efs.us-east-1.amazonaws.com:/ /mnt/efs
+          sudo mount -t nfs4 -o nfsvers=4.1,tcp,hard,timeo=600,retrans=2 fs-02bded1456fa64b56.efs.us-east-1.amazonaws.com:/ /mnt/efs \
+          || { echo "EFS mount failed!"; exit 1; }
 
       - name: Copy files to EFS
         run: sudo cp -r stuff/* /mnt/efs/
@@ -63,9 +64,6 @@ jobs:
       - name: Check status-page logs
         run: docker logs status-page
       
-      - name: Test Application with cURL
-        run: curl -fL http://localhost:8001 || exit 1
-      
       - name: Test Connection to RDS PostgreSQL Instance
         run: |
           PSQL_TEST_COMMAND="PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h neta-fred-database.cx248m4we6k7.us-east-1.rds.amazonaws.com -U ${{ secrets.DB_USERNAME }} -d postgres -c 'SELECT 1;'"
@@ -75,6 +73,14 @@ jobs:
           else
             echo "RDS PostgreSQL connection successful."
           fi
+      
+      - name: Run Snyk Security Scan
+        uses: snyk/actions/docker@master
+        with:
+          image: stuff-status-page:latest
+          args: --severity-threshold=high
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
   push-to-ecr:
     needs: build-and-test
@@ -86,7 +92,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+          aws-region: $AWS_REGION
     
       - name: Login to Amazon ECR
         uses: aws-actions/amazon-ecr-login@v1
@@ -99,7 +105,7 @@ jobs:
         run: |
           LATEST_VERSION=$(aws ecr describe-images --repository-name neta-fred/final-project \
           --query 'imageDetails[*].imageTags' --output json | \
-          jq -r 'flatten | select(.[] | test("^stuff-status-page-version-[0-9]+$"))' | \
+          jq -r 'flatten | .[] | select(test("^stuff-status-page-version-[0-9]+$"))' | \
           grep -o '[0-9]*' | sort -nr | head -n1)
         
           if [[ -z "$LATEST_VERSION" ]]; then
@@ -117,12 +123,15 @@ jobs:
       - name: Tag the Image as Latest and Push to ECR
         run: |
           docker tag stuff-status-page:latest $REPO_URI:latest
-          docker push $REPO_URI:latest  # Push the image with the latest tag
+          docker push $REPO_URI:latest
     
       - name: Stop and Remove Containers
         run: docker-compose -f stuff/compose.yaml down
     
       - name: Cleanup Running Containers
         run: |
-          docker ps -q | xargs -r docker stop
-          docker ps -aq | xargs -r docker rm
+          docker ps -q | xargs -r docker stop || true
+          docker ps -aq | xargs -r docker rm || true
+      
+      - name: Set Correct Permissions Inside Container
+        run: sudo chown -R 100:102 ./opt
